apiVersion: v1
kind: ReplicationController
metadata:
  name: vertex-rc
spec:
  replicas: 3
  selector:
    app: myvertexpod
  template:
    metadata:
      labels:
        app: myvertexpod
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80

