apiVersion: v1
kind: Service
metadata:
  name: vertex-svc
  labels:
     app: myvertexpod
spec: 
  type: NodePort
  ports:
   - port: 80
     nodePort: 30001
     protocol: TCP    
  selector:       
    app: myvertexpod