apiVersion: v1
kind: service
metadata:
  name: vertex-svc
  labels:
     app: myvertexapp
spec: 
  type: Nodeport
  ports:
   - port: 80
     nodePort: 30001
     protocol: TCP    
  selector:       
    app: myvertexapp